version: "3.2"

services:
  shields:
    image: shields

    deploy:
      replicas: 1

      restart_policy:
        condition: any

    env_file: /home/teamcity/shields.env

    environment:
      # Base URL for redirects etc.
      BASE_URL: "http://localhost:8080"
      # Where your homepage is, if different
      FRONTEND_REDIRECT_URL: "https://javacord.org/"

      # Server settings
      PORT: 80
      BIND_ADDRESS: "::"

      # GitHub settings
      GITHUB_URL: "https://api.github.com"

    networks:
      - shields

    ports:
      - "8080:80"

  javadoc_proxy:
    image: javadoc_proxy

    deploy:
      replicas: 1

      restart_policy:
        condition: any

    networks:
      - javadoc_proxy

    ports:
      - "8081:80"

  gradle-build-cache:
    image: gradle/build-cache-node

    deploy:
      replicas: 1

      restart_policy:
        condition: any

    volumes:
      - gradle-build-cache-data:/data

    networks:
      - gradle-build-cache

    # if the web interface of the cache node is needed
    #ports:
    #  - "5071:5071"

  mysql:
    image: mysql:5.7

    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_bin", "--binlog-format=MIXED"]

    deploy:
      replicas: 1

      restart_policy:
        condition: any

    # Uncomment environment and secrets for first start to setup database, then uncomment again
    #
    #environment:
    #  MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_password"
    #  MYSQL_DATABASE: "teamcity"
    #  MYSQL_USER: "teamcity"
    #  MYSQL_PASSWORD_FILE: "/run/secrets/mysql_teamcity_password"
    #
    #secrets:
    #  - source: mysql_root_password
    #    uid: '999'
    #    gid: '999'
    #    mode: 0400
    #
    #  - source: mysql_teamcity_password
    #    uid: '999'
    #    gid: '999'
    #    mode: 0400

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - mysql

    # if the MySQL port is needed from the host
    #ports:
    #  - "3306:3306"

  teamcity:
    image: jetbrains/teamcity-server:2018.1.3

    deploy:
      replicas: 1

      restart_policy:
        condition: any

    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
      - /run/docker.sock:/run/docker.sock

    networks:
      - mysql

    ports:
      - "8111:8111"

#secrets:
#  mysql_root_password:
#    external: true
#
#  mysql_teamcity_password:
#    external: true

volumes:
  gradle-build-cache-data:
  mysql-data:
  teamcity-data:
  teamcity-logs:

networks:
  shields:
  javadoc_proxy:
  gradle-build-cache:
    # allow the building containers to attach to the network
    attachable: true
  mysql:
